CREATE SEQUENCE SEQ_ALUNO;

CREATE TABLE ALUNO(
    ALUNOID NUMERIC(20),
    PESSOAID NUMERIC(20) NOT NULL,
    CONSTRAINT PK_ALUNO PRIMARY KEY (ALUNOID),
    CONSTRAINT FK_ALUNO_PESSOA FOREIGN KEY (PESSOAID) REFERENCES PESSOA (PESSOAID)
);