CREATE SEQUENCE SEQ_CONTATO;

CREATE TABLE CONTATO(
    CONTATOID NUMERIC(20),
    PESSOAID NUMERIC(20),
    TELEFONE VARCHAR(15),
    EMAIL VARCHAR (100),
    CONSTRAINT PK_CONTATO PRIMARY KEY (CONTATOID),
    CONSTRAINT FK_CONTATO_PESSOA FOREIGN KEY (PESSOAID) REFERENCES PESSOA (PESSOAID)
);