CREATE SEQUENCE SEQ_ENDERECO;

CREATE TABLE ENDERECO(
    ENDERECOID NUMERIC(20) PRIMARY KEY,
    CIDADEID NUMERIC(20) NOT NULL,
    ESTADOID NUMERIC(20) NOT NULL,
    PESSOAID NUMERIC(20),
    RUA VARCHAR (200),
    NUMERO NUMERIC(10),
    CONSTRAINT FK_ENDERECO_CIDADE FOREIGN KEY  (CIDADEID) REFERENCES CIDADE (CIDADEID),
    CONSTRAINT FK_ENDERECO_ESTADO FOREIGN KEY  (ESTADOID) REFERENCES ESTADO (ESTADOID),
    CONSTRAINT FK_ENDERECO_PESSOA FOREIGN KEY  (PESSOAID) REFERENCES PESSOA (PESSOAID)
);